export const PRODUCT_TAGS = [
  "canadian",
  "certclean",
  "chemical free",
  "diary free",
  "ewg verified",
  "ecocert",
  "fair trade",
  "gluten free",
  "hypoallergenic",
  "natural",
  "no talc",
  "non-gmo",
  "organic",
  "peanut free product",
  "sugar free",
  "usda organic",
  "vegan free",
  "alcohol free",
  "cruelty free",
  "oil free",
  "purpicks",
  "silicon free",
  "water free",
];
